version: "3.5"
services:
  master:
    image: "master_node:1.0"
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - localhost
    command:
      -m http://localhost:8080 -s http://localhost:8081
    volumes:
      - "master_node:/master_node"

  secondary:
    image:  "secondary_node:1.0"
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - localhost
    command:
      -h localhost -p 8081 -d 10
    volumes:
      - "secondary_node:/secondary_node"

volumes:
  master_node:
    driver: local
  secondary_node:
    driver: local

networks:
  localhost:
    driver: bridge
